### ISSUE TITLE
Manual install Ubuntu 20.04 out of 12GB VRAM

### ISSUE THREAD

**Issue by Ken-g6** [pinokiofactory/cogstudio#9]
I successfully installed manually on Ubuntu 20.04 using Python 3.10.  But attempting to create a video with txt2video failed:

> Traceback (most recent call last):
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
>     response = await route_utils.call_process_api(
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
>     result = await self.call_function(
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
>     prediction = await anyio.to_thread.run_sync(  # type: ignore
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2357, in run_sync_in_worker_thread
>     return await future
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 864, in run
>     result = context.run(func, *args)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
>     response = f(*args, **kwargs)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
>     response = f(*args, **kwargs)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/cogstudio.py", line 685, in generate
>     latents, seed = infer(
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/cogstudio.py", line 217, in infer
>     init(name, image_input, video_input, dtype, full_gpu)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/cogstudio.py", line 57, in init
>     init_txt2vid(name, dtype_str, full_gpu)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/cogstudio.py", line 84, in init_txt2vid
>     dtype = init_core(name, dtype_str)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/cogstudio.py", line 67, in init_core
>     pipe = CogVideoXPipeline.from_pretrained(name, torch_dtype=dtype).to(device)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 447, in to
>     module.to(device, dtype)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
>     return self._apply(convert)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
>     module._apply(fn)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 853, in _apply
>     self._buffers[key] = fn(buf)
>   File "/userfiles/ken/ai/CogVideo/inference/gradio_composite_demo/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in convert
>     return t.to(
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 66.00 MiB. GPU 

nvidia-smi showed:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070        Off | 00000000:01:00.0  On |                  N/A |
|  0%   40C    P2              32W / 100W |  11950MiB / 12282MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1557      G   /usr/lib/xorg/Xorg                          166MiB |
|    0   N/A  N/A    940209      G   /usr/lib/firefox/firefox                    129MiB |
|    0   N/A  N/A   2595498      C   python                                    11636MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by xnapxx** [comment]
same problem here on arch linux with rtx 3060 12gb
